### ISSUE TITLE
Missing Access

### ISSUE THREAD

**Issue by GriShafir** [Cowation/DSiCord#2]
Every time when I try to connect to DSiCord with DSi Browser using tutorial in the previous issue, I get this error in the console:
```
DiscordAPIError: Missing Access
    at RequestHandler.execute (D:\repos\DSiCord\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\repos\DSiCord\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async GuildManager.fetch (D:\repos\DSiCord\node_modules\discord.js\src\managers\GuildManager.js:273:20)
    at async D:\repos\DSiCord\index.js:59:17 {
  method: 'get',
  path: '/guilds/790647809460142080?with_counts=true',
  code: 50001,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }
}
```
and "Not Found" in the website I try to connect to. Any ideas?

**Comment by Cowation** [comment]
Just realized you probably already put in the .env file. I'll try and see if there's anything else that's causing the error.

**Comment by Cowation** [comment]
Alright! I found out the issue. In `index.js`, there are two variables: `GUILD_ID` and `CHANNEL_ID`. These are both used to specify the default server and channel that DSiCord will go to when you connect. Replace these two variables with valid IDs that your bot has access to (Make sure the guild is one your bot is already in and that the channel is one your bot can send messages in)

You can enable "Developer Mode" in Discord by going to Settings > Advanced > Developer Mode. You can then right click your server and click "Copy ID" and do the same for the channel.

Let me know if anything else happens!

**Comment by GriShafir** [comment]
Console still writes the same problem, and so is the website. Though, I see bot goes online when I go to the website.

**Comment by Cowation** [comment]
That's strange. Would you mind sending a screenshot of the console? Are you still getting a 4XX error?

**Comment by Cowation** [comment]
The error in question you are facing is a Discord API issue, in which your bot isn't able to access the server you've set in `index.js`. My best bet is to invite the bot with full permissions and ensure you've typed in both variables correctly. Otherwise, this isn't really an issue with DSiCord.

**Comment by Cowation** [comment]
I should also mention the bot should be invited to the server and channel you specify. This needs to be done manually because it's not able to do so on its own.
